### ISSUE TITLE
Can not add a feed

### ISSUE THREAD

**Issue by chrisspiegl** [halfdan/piwik-feedannotation-plugin#1]
I do the following:
- Go to the FeedAnnotation settings
- Select the site I would like to add a feed to
- Enter the feed URL
- Click 'Save'
- **ERROR**: It now takes me right to the dashboard

Hope you can fix this. I would love to use this!

**Comment by halfdan** [comment]
Indeed. Seems like I didn't push the latest version. I'll update tomorrow. Thanks for the report!

**Comment by jthingelstad** [comment]
Same issue here. I'll look for tomorrows push.
