### ISSUE TITLE
Add Feed only via "hit enter" not via button "Save"

### ISSUE THREAD

**Issue by chrisspiegl** [halfdan/piwik-feedannotation-plugin#3]
I just pulled the changes to my installation. And first I thought adding feeds would still not work. Than I found out that:
1. If you enter the feed url and click 'Save' it does not work.
2. If you enter the feed url and hit 'enter-key' it does add the feed url.

I use piwik v1.11.1

**Comment by halfdan** [comment]
Works for me? Can you try and clear the cache in tmp/templates_c?

**Comment by Putr** [comment]
Had the same problem after update to last version. Clear cache worked for me.

**Comment by halfdan** [comment]
Closing since it's working for me. Please let me know if the issue remains and I'll reopen.
