### ISSUE TITLE
Update plugin for Piwik 2.0

### ISSUE THREAD

**Issue by halfdan** [halfdan/piwik-feedannotation-plugin#8]
Piwik 2.0 has some major changes and the plugin should be updated to work with 2.0.

**Comment by chrisspiegl** [comment]
Apperently it is not in the store yet and Piwik 2.0 is already out there.

Additionally if I am running the plugin with 2.0 right now it gives an error because there is still some zend stuff inside.

**Comment by halfdan** [comment]
Correct - this was updated for Piwik 2.0a12 a while back. I need to look into updating this for the release version and will push it to the marketplace after.

**Comment by chrisspiegl** [comment]
Any idea about the timeframe?

**Comment by halfdan** [comment]
End of Week / Weekend probably.
